"""baseline schema

Revision ID: 972b281d63dc
Revises: 
Create Date: 2026-07-15 14:41:49.657351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972b281d63dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'data_scientist', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('dataset_name', sa.String(length=100), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('f1_weighted', sa.Float(), nullable=True),
    sa.Column('f1_macro', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('extra_metrics', sa.JSON(), nullable=True),
    sa.Column('model_artifact_path', sa.String(length=500), nullable=True),
    sa.Column('preprocessor_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=10), nullable=True),
    sa.Column('proto', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('dur', sa.Float(), nullable=True),
    sa.Column('sbytes', sa.Integer(), nullable=True),
    sa.Column('dbytes', sa.Integer(), nullable=True),
    sa.Column('sttl', sa.Integer(), nullable=True),
    sa.Column('dttl', sa.Integer(), nullable=True),
    sa.Column('sloss', sa.Integer(), nullable=True),
    sa.Column('dloss', sa.Integer(), nullable=True),
    sa.Column('spkts', sa.Integer(), nullable=True),
    sa.Column('dpkts', sa.Integer(), nullable=True),
    sa.Column('ct_srv_src', sa.Integer(), nullable=True),
    sa.Column('ct_dst_ltm', sa.Integer(), nullable=True),
    sa.Column('ct_src_dport_ltm', sa.Integer(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('attack_cat', sa.String(length=30), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_events_attack_cat'), 'network_events', ['attack_cat'], unique=False)
    op.create_index(op.f('ix_network_events_label'), 'network_events', ['label'], unique=False)
    op.create_index('ix_network_label_cat', 'network_events', ['label', 'attack_cat'], unique=False)
    op.create_table('system_call_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('split', sa.String(length=20), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('parent_process_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mount_namespace', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('args_num', sa.Integer(), nullable=True),
    sa.Column('return_value', sa.Integer(), nullable=True),
    sa.Column('evil', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_syscall_evil_event', 'system_call_events', ['evil', 'event_id'], unique=False)
    op.create_index(op.f('ix_system_call_events_event_id'), 'system_call_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_system_call_events_evil'), 'system_call_events', ['evil'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('event_source', sa.String(length=20), nullable=True),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.Column('predicted_label', sa.Integer(), nullable=True),
    sa.Column('predicted_class', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('true_label', sa.Integer(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='alertseverity'), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'false_positive', name='alertstatus'), nullable=True),
    sa.Column('source_dataset', sa.String(length=50), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_system_call_events_evil'), table_name='system_call_events')
    op.drop_index(op.f('ix_system_call_events_event_id'), table_name='system_call_events')
    op.drop_index('ix_syscall_evil_event', table_name='system_call_events')
    op.drop_table('system_call_events')
    op.drop_index('ix_network_label_cat', table_name='network_events')
    op.drop_index(op.f('ix_network_events_label'), table_name='network_events')
    op.drop_index(op.f('ix_network_events_attack_cat'), table_name='network_events')
    op.drop_table('network_events')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
